version: '3.4'

services:
  appointmentbooking.api:
    image: ${DOCKER_REGISTRY-}appointmentbookingapi
    build:
      context: .
      dockerfile: AppointmentBooking.Api/Dockerfile
    environment:
      - ConnectionStrings__db=Server=db;User Id=sa;Password=<YourStrong!Passw0rd>;Database=ReservaTurnos;Encrypt=False;TrustServerCertificate=True
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "<YourStrong!Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
